name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
env:
  image_name: transaction_api

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Get SHA
        id: get_sha
        run: echo "::set-output name=sha::$(echo $GITHUB_SHA | cut -c1-7)"
    outputs:
      sha: ${{ steps.get_sha.outputs.sha }}
  build:
    runs-on: ubuntu-latest
    needs: init
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ env.image_name }}:${{ needs.init.outputs.sha }} --build-arg POSTGRES_DB=${{ secrets.POSTGRES_DB }} --build-arg POSTGRES_USER=${{ secrets.POSTGRES_USER }} --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        docker tag ${{ env.image_name }}:${{ needs.init.outputs.sha }} ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ env.image_name }}:${{ needs.init.outputs.sha }}
        docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ env.image_name }}:${{ needs.init.outputs.sha }}
